name: Deploy

#Trigger the deploy on push

on:
  push:
    branches: ["main"]
 

#authenticate on server via ssh
# run deployment scrip

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to server
        uses: actions/set-up-node@v3      
        with:
          node-version: '18'
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          port: ${{secrets.PORT}}
          key: ${{secrets.SSHKEY}}
          script: "cd htdocs/demo2.gharxpert.in/githubactions_node && ./.scripts/deploy.sh"